---
- name: Week 4 Lab
  hosts: all
  become: true

  tasks: 
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Restart service httpd, in all cases
    ansible.builtin.service:
      name: httpd
      state: restarted